### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by tsalo** [neurostuff/PyMARE#109]
In this week's scheduled CI, tests started failing: https://github.com/neurostuff/PyMARE/actions/runs/2767886868

**Comment by tsalo** [comment]
@JulioAPeraza will you have time this week to look into this?

**Comment by JulioAPeraza** [comment]
Sure!

**Comment by JulioAPeraza** [comment]
I think the issue comes from `scipy.optimize.minimize` in `pymare.stats.q_profile`, after the latest scipy release.
https://github.com/neurostuff/PyMARE/blob/19af39959baa34eea4a34aa564945a0cbef30f62/pymare/stats.py#L111-L113
