### ISSUE TITLE
Mac python 3.9 error

### ISSUE THREAD

**Issue by jdkent** [neurostuff/PyMARE#116]
=========================== short test summary info ============================
FAILED pymare/tests/test_effectsize_base.py::test_compute_measure - assert False
 +  where False = <function array_equal at 0x11151[155](https://github.com/neurostuff/PyMARE/actions/runs/4969728472/job/13460184099#step:6:156)0>(array([4, 2]), (array([4, 2]) - array([5. , 2.5])))
 +    where <function array_equal at 0x111511550> = np.array_equal
 +    and   array([4, 2]) = 0    4\n1    2\nName: m1, dtype: int64.values
 +    and   array([5. , 2.5]) = 0    5.0\n1    2.5\nName: m2, dtype: float64.values
============ 1 failed, 71 passed, 2 skipped, 17 warnings in 25.64s =============

https://github.com/neurostuff/PyMARE/actions/runs/4969728472/job/13460184099

**Comment by JulioAPeraza** [comment]
I think this was addressed here: https://github.com/neurostuff/PyMARE/pull/118/files#diff-aaa3af340f9e3507b5a26d2d2f129848e514d9c64a929b61d1ab7e9c6f3ca062
the list of `solutions` had a different ordering than the `symbols`. Doing `solutions = [[solutions[s] for s in symbols]]` solved the issue.

**Comment by jdkent** [comment]
closing
