### ISSUE TITLE
Read expression list from JSON file and allow user to load custom list

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/PyMARE#14]
With an eye to NiMARE integration, it would be nice to allow users to override the list of expressions used in effect size conversion. An easy way to support this would be to read the expression in from JSON, and then create a manager/config class that can take an external JSON file containing the expressions).

**Comment by tyarkoni** [comment]
Closing this; we do now read from a JSON list as of #26, and I think user-supplied expression lists are probably a bit of a liability at the moment (because they could interfere with the predefined expressions), without a clear use case.

**Comment by tsalo** [comment]
I thought the use-case was https://github.com/neurostuff/NiMARE/issues/170 (esp. https://github.com/neurostuff/NiMARE/issues/170#issuecomment-595459194)?

**Comment by tyarkoni** [comment]
Ohhh, right, I'd forgotten about that. Thanks for the reminder. Re-opening.

**Comment by tsalo** [comment]
In https://github.com/neurostuff/NiMARE/issues/170#issuecomment-626898050, you ended up moving away from this idea, and now that NiMARE has its own set of transformations I think there isn't a use-case. Should we close this?
