### ISSUE TITLE
Releases on Zenodo

### ISSUE THREAD

**Issue by tsalo** [neurostuff/PyMARE#31]
Now that PyMARE is releasing on PyPi, should we also do the same on Zenodo?

**Comment by tyarkoni** [comment]
Oh, good idea, I'll add that.

**Comment by tyarkoni** [comment]
BTW, have you started wrapping PyMARE in NiMARE yet? If not, I'm happy to take a stab at it. I'll probably just replace my existing PR wholesale.

**Comment by tsalo** [comment]
No I haven't started that yet. I'm not familiar enough with PyMARE yet. I was going to take a crack at the docs and some examples to help myself with that first.

**Comment by tyarkoni** [comment]
Sounds good—docs and examples would be great. I have some thoughts on how we might want to implement the wrapper classes, but will open an issue for discussion on the NiMARE repo.

**Comment by tsalo** [comment]
I've enabled the releases on Zenodo's end, so the next time you make a release we just need to copy the auto-generated DOI badge from Zenodo into the README.
