### ISSUE TITLE
Results objects break if user called fit() rather than fit_dataset()

### ISSUE THREAD

**Issue by tyarkoni** [neurostuff/PyMARE#52]
The various results classes all currently require access to the estimator's last-fitted `Dataset`, which won't exist now following the API change to allow `fit()` to be called with numpy arrays. The solution is to either implicitly create and store a `Dataset`, which would be easier, but feels counterproductive (since the point of eliminating `Dataset` inputs from `fit()` was to cut down overhead), or to directly store references to the input arrays rather than to a `Dataset` in the estimator (in which case we have to add a bunch of code to every estimator, and lose some of the benefits of the `Dataset abstraction).

**Comment by tsalo** [comment]
Based on local testing with NiMARE, I think this is specific to the `CombinationTest` classes.
