### ISSUE TITLE
Missing data imputation method , and small study effect

### ISSUE THREAD

**Issue by safoora174** [neurostuff/PyMARE#55]
Hi
Is it possible to run missing data imputation method and small study effect in the package?

**Comment by safoora174** [comment]
@tsalo thank you, I thin I post it in a wrong place

**Comment by tyarkoni** [comment]
@safoora174 there aren't currently any plans to support imputation in PyMARE; it seems out of scope. There are other Python packages you can use for imputation—e.g., see the [scikit-learn docs](https://scikit-learn.org/stable/modules/impute.html). Once you have an imputed dataset, you can then feed it to PyMARE.

**Comment by safoora174** [comment]
@tyarkoni thank you so much. I have read nearly all the missing data imputation packages in python, such as autoimpute, missingpy,impute , but non of them using methods which are used in metamiss function of metasense package in R. They do not use methods such as ACA, IMOR, GH.
Thanks for your comment

**Comment by safoora174** [comment]
Dear Taylor,

I wrote some of missing data Imputation method myself and after analysis, I
have the summary risk ratios for each analyses. Do you know how I can
combine them in one forest plot? I searched a lot but couldn't find a
useful method. I found arviz , but I do not know how combine them in one
plot and how I can change the code to change the shape of each study plot
to a diamond one. Sorry for the confusion

Regards,
Safoora

**Comment by tsalo** [comment]
Hi Safoora,

I'm sorry to say that standard meta-analyses are mostly outside of my area of expertise. I don't know how to generate forest plots for summary risk ratios, or even generally, in Python.

**Comment by safoora174** [comment]
Thank you so much dear Taylor.
