### ISSUE TITLE
Invalid data type for einsum

### ISSUE THREAD

**Issue by tsalo** [neurostuff/PyMARE#57]
I am trying to run a meta-analysis with the DerSimonian-Laird estimator on a toy example, but I am getting an odd error in `einsum`.

### Data

[meta_data.txt](https://github.com/neurostuff/PyMARE/files/5639479/meta_data.txt)

|    |       educ |        age |   intercept |   educ_var |    age_var |   intercept_var | site   |   sample_size |
|---:|-----------:|-----------:|------------:|-----------:|-----------:|----------------:|:-------|--------------:|
|  0 | -0.0343665 |  0.0685226 |    0.621957 |   0.053402 | 0.00518936 |        0.382996 | a      |           833 |
|  1 |  0.337121  |  0.0831343 |   -0.754383 |   0.257379 | 0.0256497  |        1.6269   | b      |            42 |
|  2 | -0.131197  |  0.0794553 |   -0.551759 |   0.341987 | 0.027644   |        2.39215  | c      |            22 |
|  3 |  0.56336   |  0.125616  |   -4.06326  |   0.29117  | 0.0278645  |        2.23611  | d      |            12 |
|  4 |  1.47761   |  0.0410448 |   -4.48134  |   0.772219 | 0.0675251  |        3.46781  | e      |            10 |
|  5 |  0.398824  | -0.0435086 |    3.97413  |   0.687461 | 0.0618968  |        5.08491  | f      |             7 |
|  6 |  0.122459  | -0.016405  |    4.29702  |   0.437787 | 0.0430945  |        2.63758  | g      |            18 |

### Code

```python
import pandas as pd
from pymare.estimators import DerSimonianLaird
from pymare import Dataset

meta_df = pd.read_table("meta_data.txt")

metamodel = DerSimonianLaird()
dset = Dataset(
    y=meta_df[["age", "educ"]].values, 
    v=meta_df[["age_var", "educ_var"]].values,
    add_intercept=True,
)
metamodel.fit_dataset(dset)
```

### Traceback

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-26c7cae08262> in <module>
      5     add_intercept=True,
      6 )
----> 7 metamodel.fit_dataset(dset)

~/anaconda/envs/python3/lib/python3.6/site-packages/pymare/estimators/estimators.py in fit_dataset(self, dataset, *args, **kwargs)
     88 
     89         all_kwargs.update(kwargs)
---> 90         self.fit(*args, **all_kwargs)
     91         self.dataset_ = dataset
     92 

~/anaconda/envs/python3/lib/python3.6/site-packages/pymare/estimators/estimators.py in fit(self, y, v, X)
    195 
    196         # Estimate initial betas with WLS, assuming tau^2=0
--> 197         beta_wls, inv_cov = weighted_least_squares(y, v, X, return_cov=True)
    198 
    199         # Cochrane's Q

~/anaconda/envs/python3/lib/python3.6/site-packages/pymare/stats.py in weighted_least_squares(y, v, X, tau2, return_cov)
     24 
     25     # Einsum indices: k = studies, p = predictors, i = parallel iterates
---> 26     wX = np.einsum('kp,ki->ipk', X, w)
     27     cov = wX.dot(X)
     28 

<__array_function__ internals> in einsum(*args, **kwargs)

~/anaconda/envs/python3/lib/python3.6/site-packages/numpy/core/einsumfunc.py in einsum(out, optimize, *operands, **kwargs)
   1348         if specified_out:
   1349             kwargs['out'] = out
-> 1350         return c_einsum(*operands, **kwargs)
   1351 
   1352     # Check the kwargs to avoid a more cryptic error later, without having to

TypeError: invalid data type for einsum
```

**Comment by tyarkoni** [comment]
I can't reproduce this on my end, unfortunately (or maybe fortunately)... maybe try updating the dependencies (pandas and numpy being the most likely culprits)?

**Comment by tsalo** [comment]
Oh wow.... sorry about this! It looks like the problem was that the DataFrame contained objects instead of floats, which saving to, and loading from, a file fixed.
