### ISSUE TITLE
Invalid (zero) p-values in Fisher's results

### ISSUE THREAD

**Issue by tsalo** [neurostuff/PyMARE#61]
In https://github.com/neurostuff/NiMARE/pull/432 we saw some empty spots in what should be highly-significant regions in an example Fisher's meta-analysis (see screen shot below). Based on the warning traceback, it looks like the problem stems from PyMARE, rather than NiMARE.

<img width="742" alt="Screen Shot 2021-03-05 at 11 18 43 AM" src="https://user-images.githubusercontent.com/8228902/110145524-88056f00-7da7-11eb-8da4-b6bca82e44b8.png">

**Comment by tyarkoni** [comment]
Ah, yeah, thanks for catching this. Looks like we need to replace zeros with machine epsilon.

**Comment by tsalo** [comment]
It looks like only CombinationTestResults aren't cropped (see below):

https://github.com/neurostuff/PyMARE/blob/ecc71fa6c469bf49f33e85c0db14a348f7876f68/pymare/results.py#L257-L260

We can probably use @jdkent's [`z_to_p()`](https://github.com/neurostuff/NiMARE/blob/c465d90d86bf50d9f30b0460c8b232e14fa83107/nimare/transforms.py#L448-L474) from https://github.com/neurostuff/NiMARE/pull/446.

While we're at it, I think it would be worth it to synchronize the null_to_p conversion across packages. Here's PyMARE's approach:

https://github.com/neurostuff/PyMARE/blob/ecc71fa6c469bf49f33e85c0db14a348f7876f68/pymare/results.py#L213-L224

Should we just move all of NiMARE's stat conversion functions to PyMARE?

**Comment by tsalo** [comment]
I think it would be a good idea to resolve this before the next NiMARE release. I can open a PR to duplicate some of the functions in NiMARE that deal with this issue, but I'm still unsure about whether we should _move_ NiMARE's conversion functions to PyMARE or not. @jdkent @tyarkoni what would you prefer?

**Comment by tsalo** [comment]
Fixing t_to_z in NiMARE seems to have resolved this issue completely. I'm not sure if we want to get ahead of any potential future problems and "fix" this in PyMARE as well, or if it's fine to address the immediate bug in NiMARE and close this.

**Comment by jdkent** [comment]
I would say keep this open, but have it be a low priority.

> but I'm still unsure about whether we should move NiMARE's conversion functions to PyMARE or not.

My heuristic currently would be to move statistical functions over that would aid in meta-analysis of arrays of data and are not dependent (or unique to) brain images, which I believe the transforms are general.

**Comment by tsalo** [comment]
I think most of the data type transforms _could_ be moved here, but it's possible that they would conflict with the expressions that are already here.
