### ISSUE TITLE
Settings for metafor comparison

### ISSUE THREAD

**Issue by tsalo** [neurostuff/PyMARE#75]
I'm having trouble determining how metafor was called to produce the values we're testing against in our CI. @tyarkoni do you happen to have that info available?

For example, to compare DerSimonian-Laird estimator results, I did the following:

## metafor

```R
library(metafor)

y <- c(-1, 0.5, 0.5, 0.5, 1, 1, 2, 10)
v <- c(1, 1, 2.4, 0.5, 1, 1, 1.2, 1.5)

mod <- rma(y, v, method="DL")
print(mod)
```

```Text
Random-Effects Model (k = 8; tau^2 estimator: DL)

tau^2 (estimated amount of total heterogeneity): 7.6337 (SE = 4.8874)
tau (square root of estimated tau^2 value):      2.7629
I^2 (total heterogeneity / total variability):   88.02%
H^2 (total variability / sampling variability):  8.35

Test for Heterogeneity:
Q(df = 7) = 58.4539, p-val < .0001

Model Results:

estimate      se    zval    pval    ci.lb   ci.ub 
  1.7679  1.0491  1.6852  0.0920  -0.2883  3.8241  . 

---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

## PyMARE

```python
import numpy as np
from pymare import Dataset, estimators

y = np.array([-1, 0.5, 0.5, 0.5, 1, 1, 2, 10])
v = np.array([1, 1, 2.4, 0.5, 1, 1, 1.2, 1.5])
X = np.ones(y.shape)
dset = Dataset(y=y, v=v, X=X)

est = estimators.DerSimonianLaird()
est.fit_dataset(dset)
res = est.summary()
res.to_df()
```

| name      |   estimate |       se |   z-score |   p-value |   ci_0.025 |   ci_0.975 |
|:----------|-----------:|---------:|----------:|----------:|-----------:|-----------:|
| intercept |   0.884331 | 0.528961 |   1.67182 | 0.0945589 |  -0.152414 |    1.92108 |
| 0         |   0.884331 | 0.528961 |   1.67182 | 0.0945589 |  -0.152414 |    1.92108 |

## Summary

The results look quite different (e.g., the metafor estimate is >2x the PyMARE estimate), so I think I'm doing it wrong.

**Comment by tyarkoni** [comment]
I think you're feeding intercepts to the `Dataset` in `X`, but leaving `add_intercept` set to `True`. So you get two identical columns of 1s, which is why both estimates look identical. Try dropping `X` (or setting intercept to `False`) and see if that fixes it.

**Comment by tsalo** [comment]
Oh, you're right. Thanks!

|    |   name |   estimate |      se |   z-score |   p-value |   ci_0.025 |   ci_0.975 |
|---:|-------:|-----------:|--------:|----------:|----------:|-----------:|-----------:|
|  0 |      0 |    1.76788 | 1.04909 |   1.68515 | 0.0919593 |  -0.288304 |    3.82407 |
